export const values = {
  Salary: "",
  "Additional Income": "",
  "Mortgage/Rent": "",
  HOA: "",
  "Housing/Renters Insurance": "",
  Utilities: "",
  Internet: "",
  "Cable/Streaming": "",
  Phone: "",
  "Car Payment": "",
  "Car Insurance": "",
  Gas: "",
  Groceries: "",
  Pet: "",
  Clothing: "",
  Medical: "",
  Entertainment: "",
  "Student Loans": "",
  Books: "",
  "Savings/Emergency Fund": "",
  Investments: "",
  Retirement: ""
};
